version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6384
    depends_on:
      - redis
    env_file:
      - .env.local
    restart: unless-stopped

  redis:
    image: redis:7.2-alpine
    ports:
      - "6384:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

volumes:
  redis-data:
