version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    ports:
      - "6384:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

volumes:
  redis-data:
