version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    ports:
      - "6384:6379"
      # 6384 external port for the redis server
    volumes:
      - redis-data:/data
    command: redis-server --requirepass your_secure_redis_password_here --appendonly yes
    restart: unless-stopped

volumes:
  redis-data:
